session_name: config
start_directory: /home/aedison
windows:
- window_name: root
  options: {}
  panes:
  - focus: 'true'
    shell_command: 
- window_name: dbatasker
  focus: 'true'
  options: {}
  panes:
  - focus: 'true'
    shell_command: 
